resolver: lts-12.8

packages:
- '.'

extra-deps:
- cabal2nix-2.11
- hpack-0.29.6 # dependency of cabal2nix-2.10.0
- infer-license-0.2.0 # dependency of hpack-0.29.6

nix:
  packages: [zlib,gmp,git,pcre,openssl]

ghc-options:
  stack2nix: -Werror
