resolver: lts-9.20

packages:
- '.'
# https://github.com/peti/hackage-db/pull/7
- location:
   git: https://github.com/domenkozar/hackage-db
   commit: 0b58f1062d0a87b06bbae343d3c5a2f86ba26537
  extra-dep: true
# https://github.com/NixOS/cabal2nix/pull/322
- location:
   git: https://github.com/NixOS/cabal2nix
   commit: e72fbdfe57941627633006fa1fb4003e26619424
  extra-dep: true

extra-deps:
- stack-1.6.3
- Cabal-2.0.1.1
- bindings-uname-0.1
- path-0.6.1
- path-io-1.3.3
- ansi-terminal-0.7.1.1
- ansi-wl-pprint-0.6.8.1
- extra-1.6.2
- hpack-0.21.2
- unliftio-0.2.1.0

flags: {}

nix:
  packages: [zlib,gmp,git,pcre,openssl]

extra-package-dbs: []

ghc-options:
  stack2nix: -Werror
