resolver: lts-9.14

packages:
- '.'
- location:
   git: https://github.com/commercialhaskell/stack.git
   commit: 7bddfaf7f9f8cd9ec1c710fa83e77262e494eee4
  extra-dep: true

extra-deps:
- hnix-0.3.4
- bindings-uname-0.1
- Cabal-2.0.0.2
- cabal2nix-2.7
- hackage-db-2.0
- path-0.6.1
- path-io-1.3.3

flags: {}

nix:
  packages: [zlib,gmp,git,pcre,openssl]

extra-package-dbs: []
