resolver: lts-9.0

packages:
- '.'
- location:
   git: https://github.com/commercialhaskell/stack.git
   commit: 279744b934513454d5a11bae870432432edb196a
  extra-dep: true

extra-deps:
- hnix-0.3.4

flags: {}

nix:
  packages: [zlib,gmp]

extra-package-dbs: []
